# Generated by Django 3.0.10 on 2020-10-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('search_name', models.CharField(max_length=40)),
                ('rank', models.FloatField()),
                ('search_count', models.IntegerField()),
                ('link', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=5)),
                ('postnum', models.IntegerField()),
                ('search_type', models.CharField(max_length=50)),
                ('search_name2', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('latitud', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=15)),
                ('search_type', models.CharField(max_length=50)),
                ('search_count', models.IntegerField()),
                ('postnum', models.IntegerField()),
                ('YMD', models.CharField(max_length=8)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DB_name',
        ),
    ]
