# Generated by Django 3.0.10 on 2020-10-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20201019_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmdata',
            name='search_name',
            field=models.CharField(max_length=40),
        ),
    ]
